export const ADD_VIDEO_LIST_ITEM = 'ADD_VIDEO_LIST_ITEM';
export const ADD_VIDEO_IFRAME = 'ADD_VIDEO_IFRAME';
export const CLEAR_VIDEO_LIST = 'CLEAR_VIDEO_LIST';
export const ADD_CHANNEL_THUMBNAIL = 'ADD_CHANNEL_THUMBNAIL';
export const RESET_STATE = 'RESET_STATE';
